// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiZ9eA4Iic3UlPdd_AseKhSlVjbpEJFHA',
    appId: '1:889932341238:web:ac26364cc4972f2bdf71d7',
    messagingSenderId: '889932341238',
    projectId: 'things-crud',
    authDomain: 'things-crud.firebaseapp.com',
    storageBucket: 'things-crud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvEy2ptVO6f2zasJ-ydJN5D_pR3OUG2ZM',
    appId: '1:889932341238:android:e53e5ea9a2371c10df71d7',
    messagingSenderId: '889932341238',
    projectId: 'things-crud',
    storageBucket: 'things-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANoJi8j_HnFhzx67YIAX_L62MaGm4q7Fg',
    appId: '1:889932341238:ios:c73f4aaadab6803bdf71d7',
    messagingSenderId: '889932341238',
    projectId: 'things-crud',
    storageBucket: 'things-crud.appspot.com',
    iosClientId: '889932341238-4fgpclg98brh663tsni8sack4cdd8dk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.things',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANoJi8j_HnFhzx67YIAX_L62MaGm4q7Fg',
    appId: '1:889932341238:ios:c73f4aaadab6803bdf71d7',
    messagingSenderId: '889932341238',
    projectId: 'things-crud',
    storageBucket: 'things-crud.appspot.com',
    iosClientId: '889932341238-4fgpclg98brh663tsni8sack4cdd8dk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.things',
  );
}
